sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build tests
script: docker-compose run --rm tests
after_success:
  - docker images
notifications:
  email: false
  slack:
    secure: o6e3f4S6885iEMvCxVSdlgvPJWq8fQLk8FsEggcO/bWRx47IyfeLR/AiH2LnYpc7QtNCin6TSSogteurn39W+yfiEiUZDR10f6mKTgpgCp8JvXeQN4BP+D2KvYvchC2roBNeoR3Z48eMbKOglvgnpdFX/8W+ZM+L79JGgmltzGkK6LbGIDP0io8w1K9ALMlU6DjONM+z7tfx8KHz/T0IY1id5PB27+HeyxHYjHlbnwBc/jDgbexrisztmmPRXPPtRtvCjxChYMjef19/+q21PaRzJdMDsZ+TKgYfKymSDQ7JLDl8JNUukgPDAJFCCguhQh4Zrk+m/kZlaSWGEWETJNZEo01MWLKzlbrEXRvbvyohiisSRh5FjGZ4E4edEEdjDD2FYny0vAiBox6zKLrOnfO5zMCDy5tPx/M7CjZpwxulykWj77qszyWeTs5hJyaebE7EjJaRm1iotHL3xWugokIDIMSMWF10/cTBTsdSGq1M9BYifvSFOphrRWTsyCwTezSAMxZD2gxMYxXhzPh6uS5Ck/Oz1Ik7q6Fqf8e8R1zr/Waj+dciSBW6quL9n6Sv6eoDvrGlrI9L/+2cyLBkXT1k/fPp5d/DA3Wjw3FPUKREify26NmKBfNDuqEvoofM8E3jtSHYVjsQVXJHoPPTriujr3LnuXWzdLmjjAFtJus=
